"""empty message

Revision ID: 3a15c0607a50
Revises: 8131f2b5e33f
Create Date: 2021-04-21 10:45:45.712437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a15c0607a50'
down_revision = '8131f2b5e33f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('update_record_info', sa.Column('u_result', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('update_record_info', 'u_result')
    # ### end Alembic commands ###
