"""empty message

Revision ID: 3f765179d267
Revises: 6c38e63acb5f
Create Date: 2021-04-20 09:34:46.965871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f765179d267'
down_revision = '6c38e63acb5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_info', sa.Column('b_relieve_date', sa.String(length=15), server_default='-', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_info', 'b_relieve_date')
    # ### end Alembic commands ###
