"""empty message

Revision ID: 6c38e63acb5f
Revises: 7dc649a3284b
Create Date: 2021-04-15 17:36:08.676052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c38e63acb5f'
down_revision = '7dc649a3284b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record_info', sa.Column('r_relieve_date', sa.String(length=18), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record_info', 'r_relieve_date')
    # ### end Alembic commands ###
