"""empty message

Revision ID: 7dc649a3284b
Revises: 
Create Date: 2021-04-15 17:21:24.288113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dc649a3284b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('b_register_num', sa.String(length=30), nullable=False),
    sa.Column('b_credit_num', sa.String(length=30), nullable=False),
    sa.Column('b_company', sa.String(length=30), nullable=True),
    sa.Column('b_charge_name', sa.String(length=10), nullable=False),
    sa.Column('b_ID', sa.String(length=18), nullable=False),
    sa.Column('b_main_type', sa.String(length=30), nullable=True),
    sa.Column('b_pro_type', sa.String(length=30), nullable=True),
    sa.Column('b_date', sa.String(length=15), nullable=True),
    sa.Column('b_state', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('c_apply_num', sa.String(length=25), nullable=False),
    sa.Column('c_name', sa.String(length=25), nullable=False),
    sa.Column('c_social_num', sa.String(length=25), nullable=False),
    sa.Column('c_size', sa.String(length=10), nullable=False),
    sa.Column('c_bank', sa.String(length=30), nullable=False),
    sa.Column('c_account', sa.String(length=30), nullable=False),
    sa.Column('c_bank_card', sa.String(length=30), nullable=False),
    sa.Column('c_charge_ID', sa.String(length=18), nullable=False),
    sa.Column('c_charge_name', sa.String(length=6), nullable=False),
    sa.Column('c_contact_name', sa.String(length=6), nullable=True),
    sa.Column('c_contact_phone', sa.String(length=25), nullable=True),
    sa.Column('c_apply_count', sa.Integer(), nullable=True),
    sa.Column('c_hard_employ_count', sa.Integer(), nullable=False),
    sa.Column('c_graduate_count', sa.Integer(), nullable=False),
    sa.Column('c_army_count', sa.Integer(), nullable=False),
    sa.Column('c_affect_person_count', sa.Integer(), nullable=False),
    sa.Column('c_poor_count', sa.Integer(), nullable=False),
    sa.Column('c_total', sa.Integer(), nullable=False),
    sa.Column('c_old_insur', sa.Float(), nullable=False),
    sa.Column('c_unemploy_insur', sa.Float(), nullable=False),
    sa.Column('c_injury_insur', sa.Float(), nullable=False),
    sa.Column('c_birth_insur', sa.Float(), nullable=False),
    sa.Column('c_medical_insur', sa.Float(), nullable=False),
    sa.Column('c_social_total', sa.Float(), nullable=False),
    sa.Column('c_general_post_subsidy', sa.Float(), nullable=False),
    sa.Column('c_special_fund_count', sa.Integer(), nullable=False),
    sa.Column('c_unemploy_fund_count', sa.Integer(), nullable=False),
    sa.Column('c_net_office', sa.Boolean(), nullable=False),
    sa.Column('c_special_fund', sa.Float(), nullable=False),
    sa.Column('c_unemploy_fund', sa.Float(), nullable=False),
    sa.Column('c_success_count', sa.Integer(), nullable=False),
    sa.Column('c_success_fund', sa.Float(), nullable=False),
    sa.Column('c_fail_count', sa.Integer(), nullable=False),
    sa.Column('c_fail_fund', sa.Float(), nullable=False),
    sa.Column('c_robot_result', sa.Boolean(), nullable=True),
    sa.Column('c_explain', sa.String(length=200), nullable=True),
    sa.Column('c_detail', sa.Text(), nullable=True),
    sa.Column('c_get_person_state', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('c_search_charge', sa.String(length=30), nullable=True),
    sa.Column('c_search_location', sa.String(length=30), nullable=True),
    sa.Column('c_person_result', sa.Boolean(), nullable=True),
    sa.Column('c_date', sa.DateTime(), nullable=True),
    sa.Column('c_identify_person', sa.String(length=10), nullable=True),
    sa.Column('c_identify_comment', sa.Text(), nullable=True),
    sa.Column('c_apply_season', sa.String(length=8), nullable=True),
    sa.Column('c_isnet', sa.Boolean(), nullable=False),
    sa.Column('c_isprovince', sa.Boolean(), nullable=False),
    sa.Column('c_isseason', sa.Boolean(), nullable=True),
    sa.Column('c_season_add_count', sa.Integer(), nullable=False),
    sa.Column('c_create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('c_update_time', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detail_pay_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('d_ID', sa.String(length=32), nullable=False),
    sa.Column('d_pay_month', sa.String(length=10), nullable=False),
    sa.Column('d_old_insur', sa.Float(), nullable=True),
    sa.Column('d_injury_insur', sa.Float(), nullable=True),
    sa.Column('d_unemploy_insur', sa.Float(), nullable=True),
    sa.Column('d_birth_insur', sa.Float(), nullable=True),
    sa.Column('d_medical_insur', sa.Float(), nullable=True),
    sa.Column('d_normal_fund', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field_mapping',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sql_table', sa.String(length=255), nullable=True),
    sa.Column('sql_key', sa.String(length=255), nullable=True),
    sa.Column('sql_zh', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hard_identify_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('h_name', sa.String(length=8), nullable=False),
    sa.Column('h_ID', sa.String(length=18), nullable=False),
    sa.Column('h_employ_type', sa.String(length=20), nullable=False),
    sa.Column('h_apply_date', sa.String(length=20), nullable=False),
    sa.Column('h_identify_date', sa.String(length=20), nullable=False),
    sa.Column('h_exit_date', sa.String(length=20), nullable=False),
    sa.Column('h_state', sa.String(length=10), nullable=False),
    sa.Column('h_ID_state', sa.String(length=10), nullable=False),
    sa.Column('h_identify_way', sa.String(length=5), nullable=False),
    sa.Column('h_apply_location', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('p_c_apply_num', sa.String(length=25), nullable=False),
    sa.Column('p_list_place', sa.String(length=10), nullable=False),
    sa.Column('p_ID_type', sa.String(length=30), nullable=False),
    sa.Column('p_ID', sa.String(length=18), nullable=False),
    sa.Column('p_name', sa.String(length=10), nullable=False),
    sa.Column('p_sex', sa.String(length=2), nullable=False),
    sa.Column('p_age', sa.Integer(), nullable=False),
    sa.Column('p_type', sa.String(length=10), nullable=False),
    sa.Column('p_hard_type', sa.String(length=10), nullable=False),
    sa.Column('p_contract_start_date', sa.String(length=10), nullable=False),
    sa.Column('p_contract_end_date', sa.String(length=10), nullable=False),
    sa.Column('p_old_insur', sa.Float(), nullable=True),
    sa.Column('p_injury_insur', sa.Float(), nullable=True),
    sa.Column('p_unemploy_insur', sa.Float(), nullable=True),
    sa.Column('p_medical_insur', sa.Float(), nullable=True),
    sa.Column('p_birth_insur', sa.Float(), nullable=True),
    sa.Column('p_society_total', sa.Float(), nullable=True),
    sa.Column('p_normal_fund', sa.Float(), nullable=True),
    sa.Column('p_apply_month', sa.Integer(), nullable=True),
    sa.Column('p_iscarry', sa.Boolean(), nullable=False),
    sa.Column('p_unemploy_register', sa.String(length=100), nullable=False),
    sa.Column('p_verify_explain', sa.String(length=100), nullable=False),
    sa.Column('p_pass_num', sa.String(length=30), nullable=True),
    sa.Column('p_social_num', sa.String(length=30), nullable=True),
    sa.Column('p_disabled_num', sa.String(length=30), nullable=True),
    sa.Column('p_isgraduate', sa.Boolean(), nullable=True),
    sa.Column('p_graduate_type', sa.String(length=20), nullable=True),
    sa.Column('p_graduate_school', sa.String(length=20), nullable=True),
    sa.Column('p_graduate_date', sa.String(length=15), nullable=True),
    sa.Column('p_pass_date', sa.String(length=15), nullable=True),
    sa.Column('p_isprovince', sa.Boolean(), nullable=False),
    sa.Column('p_help_type', sa.String(length=10), nullable=True),
    sa.Column('p_reamark', sa.Text(), nullable=True),
    sa.Column('p_new_comment', sa.Text(), nullable=True),
    sa.Column('p_identify_date', sa.String(length=15), nullable=True),
    sa.Column('p_local_area', sa.String(length=30), nullable=True),
    sa.Column('p_robot_result', sa.Boolean(), nullable=True),
    sa.Column('p_explain', sa.String(length=200), nullable=True),
    sa.Column('p_detail', sa.JSON(), nullable=True),
    sa.Column('p_medical_check', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('p_medical_update', sa.String(length=30), nullable=True),
    sa.Column('p_person_result', sa.Boolean(), nullable=True),
    sa.Column('p_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('p_identify_person', sa.String(length=10), nullable=True),
    sa.Column('p_identify_comment', sa.Text(), nullable=True),
    sa.Column('p_detail_info', sa.Boolean(), server_default='0', nullable=True),
    sa.Column('p_rollback', sa.Boolean(), server_default='0', nullable=True),
    sa.Column('p_create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('p_update_time', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('record_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('r_accept_batch', sa.String(length=25), nullable=False),
    sa.Column('r_company_name', sa.String(length=30), nullable=False),
    sa.Column('r_ID', sa.String(length=18), nullable=False),
    sa.Column('r_name', sa.String(length=8), nullable=False),
    sa.Column('r_sex', sa.String(length=2), nullable=False),
    sa.Column('r_birth', sa.String(length=18), nullable=False),
    sa.Column('r_degree', sa.String(length=10), nullable=False),
    sa.Column('r_population', sa.String(length=15), nullable=False),
    sa.Column('r_location', sa.String(length=10), nullable=False),
    sa.Column('r_register_type', sa.String(length=10), nullable=False),
    sa.Column('r_contract_start_date', sa.String(length=18), nullable=False),
    sa.Column('r_contract_end_date', sa.String(length=18), nullable=False),
    sa.Column('r_register_date', sa.String(length=18), nullable=False),
    sa.Column('r_isapply', sa.String(length=10), nullable=False),
    sa.Column('r_date_source', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_pay_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('s_ID', sa.String(length=18), nullable=False),
    sa.Column('s_pay_date', sa.String(length=6), nullable=False),
    sa.Column('s_old_base', sa.String(length=15), nullable=False),
    sa.Column('s_medical_base', sa.String(length=15), nullable=True),
    sa.Column('s_old_insur', sa.String(length=8), nullable=False),
    sa.Column('s_unemploy_insur', sa.String(length=8), nullable=False),
    sa.Column('s_injury_insur', sa.String(length=8), nullable=False),
    sa.Column('s_medical_insur', sa.String(length=8), nullable=False),
    sa.Column('s_c_old_insur', sa.String(length=8), nullable=False),
    sa.Column('s_c_unemploy_insur', sa.String(length=8), nullable=False),
    sa.Column('s_c_injury_insur', sa.String(length=8), nullable=False),
    sa.Column('s_c_medical_insur', sa.String(length=8), nullable=False),
    sa.Column('s_c_disease_insur', sa.String(length=8), nullable=False),
    sa.Column('s_c_birth_insur', sa.String(length=8), nullable=False),
    sa.Column('s_social_num', sa.String(length=30), nullable=False),
    sa.Column('s_social_c_num', sa.String(length=30), nullable=False),
    sa.Column('s_social_c_name', sa.String(length=30), nullable=False),
    sa.Column('s_social_credit_num', sa.String(length=30), nullable=False),
    sa.Column('s_medical_num', sa.String(length=30), nullable=False),
    sa.Column('s_medical_c_num', sa.String(length=30), nullable=False),
    sa.Column('s_medical_c_name', sa.String(length=30), nullable=False),
    sa.Column('s_medical_credit_num', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unemploy_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('e_serial_num', sa.String(length=30), nullable=False),
    sa.Column('e_employ_num', sa.String(length=25), nullable=False),
    sa.Column('e_ID', sa.String(length=18), nullable=False),
    sa.Column('e_name', sa.String(length=8), nullable=False),
    sa.Column('e_population', sa.String(length=10), nullable=False),
    sa.Column('e_register_num', sa.String(length=10), nullable=False),
    sa.Column('e_register_type', sa.String(length=5), nullable=False),
    sa.Column('e_start_date', sa.String(length=20), nullable=False),
    sa.Column('e_end_date', sa.String(length=20), nullable=False),
    sa.Column('e_register_date', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unemploy_info')
    op.drop_table('social_pay_info')
    op.drop_table('record_info')
    op.drop_table('person_info')
    op.drop_table('hard_identify_info')
    op.drop_table('field_mapping')
    op.drop_table('detail_pay_info')
    op.drop_table('company_info')
    op.drop_table('business_info')
    # ### end Alembic commands ###
